### ISSUE TITLE
Allow projection interfaces to be non-public

### ISSUE THREAD

**Issue by olivergierke** [SvenEwald/xmlbeam#31]
Currently projection interfaces need to be public (due to `XBProjector.ensureIsValidProjectionInterface(…)` explicitly checking). However, simply making the interface accessible should do the trick in such cases. In case that in turn throws an exception, a similar rejection exception could be raised.

**Comment by SvenEwald** [comment]
This was one of my first ideas for enhancement. I never did it because no one was asking ;-)

**Comment by olivergierke** [comment]
👍🙃

**Comment by SvenEwald** [comment]
Unfortunately, this one is harder than it looks. Interfaces need to be public due to a JLS requirement for dynamic proxies. I found no way to change the visibility of interfaces during runtime.
I tried some ASM magic to extend a synthetic public interface, but failed so far :(

**Comment by olivergierke** [comment]
That's weird, as we've produced JDK dynamic proxies for package protected interfaces in Spring Data for ages. Do you have a link handy for the JLS section that describes this requirement?

Do you see any exception if you just avoid the explicit check?

**Comment by SvenEwald** [comment]
Thanks for pointing me in the right direction. The JLS requirement I had in mind was not about the proxy interfaces, but about the proxy class. I will remove the check complete in 1.4.9.
