### ISSUE TITLE
why database connecdtions cannot release?

### ISSUE THREAD

**Issue by hebo209** [SvenEwald/xmlbeam#32]
hi,
 
    recently，i get some problem with   spring-data-mongodb,can you help me ?

the version info:
-------------------------------------------------------------

mongodb version： 3.2
spring-data-mongodb version ： 1.9.1

-------------------------------------------------------------
 Now i use spring-data-mongodb to deal with my DAO layer. but i find that the  database connections is increasing，it seems  the database connecdtions cannot release .

Thanks !

**Comment by SvenEwald** [comment]
Seems like you got the wrong project for your issue report. Plz report again in the spring-data issue tracker.
