### ISSUE TITLE
XBWrite expression creates wrong result#2 'Root/Intermediate[X='Passed']'

### ISSUE THREAD

**Issue by SvenEwald** [SvenEwald/xmlbeam#41]
`Root/Intermediate[X='Passed']` creates 

`<Root>
  <Intermediate>Value</Intermediate>
</Root>`

instead of
`<Root>
   <Intermediate>
      <X>Passed</X>
      Value
   </Intermediate>
</Root>`

**Comment by SvenEwald** [comment]
This is a bug. More strage, `Root/Intermediate[@X='Passed']` works as expected.

**Comment by SvenEwald** [comment]
Found the reason: Missing else in BuildDocumentVisitor:390.
Currently writing with predicates is not implemented for single nodes or for paths. This has to be implemented, or this case needs to throw an XBExpressionNotAllowedForWritingException.

**Comment by zhsc** [comment]
@SvenEwald Thanks for the quick response and looking into this.  I thought it was a little strange so wanted to report it. Keep up the great work!

**Comment by SvenEwald** [comment]
My analysis was not finished... the reason for this error is deeper. This is happening:
1. The node is searched and while the search does not find anything, the root element is created.
2. The predicate is applied as a write operation to the root element. So the element X is created and the value of X is set to 'Passed'. 
3. The write operation to the root element is performed. Here begins the trouble, because the child element X is removed in this process.

It is not clear what to expect when a write operation to an element is to be done. Should child elements
still exist? `The org.w3c.dom.Element.setTextValue()` implementation denies that. If text content is set to an element, all child elements are removed. This would happen to existing child nodes, too. 
So, the limitation is like this: Elements may have a text value or child elements, but not both.
This is surprising, because XML allowes such structures and reading them is fine.
I need to sleep over this... multiple times ;-)

**Comment by zhsc** [comment]
Yeah.  Seems like a strange point in the xml / Dom spec. I guess intuitively one would expect a root element node with two children: another element node of X followed by a text node of "Value".  

Away from a computer at the moment but maybe there's another api method at the node level to create such a structure vs using setTextValue?

It does create questions about where the text should go though.  I.e. before the elements or after etc. There's probably an xpath function to select the node position but that requires more work and confusion.  Seems like just appending at the time of invocation would work and let the caller order their calls appropriately. 

It does seem like the code is close to handling the situation and though.

**Comment by zhsc** [comment]
Also I believe the same situation applies in more than just the text node case.  I believe if you try to write a sub projection to that same root element with the child element created by the predicate that it will wipe out the X element. So basically it seems to always replace vs appending.  

I'm not sure if it's worthy or an attribute on XBWrite for append vs replace? 

I think the usual use case for write would be building up a document so appending seems a reasonable default.  And then XBUpdate maybe has the replace default?

**Comment by SvenEwald** [comment]
Fixed in 1.4.11. Setting text content will not delete child nodes any more. I doubt that anyone relied on the previous behaviour. So this should be an improvement in any case.

**Comment by zhsc** [comment]
Awesome!  Thanks for the fast response!
