### ISSUE TITLE
ProjectionFactory gone package protected in 1.4.11

### ISSUE THREAD

**Issue by olivergierke** [SvenEwald/xmlbeam#45]
`ProjectionFactory` has been made package private in 1.4.11 which is a breaking API change and an unfortunate one as it's kind of neat to be able to only hold a reference to the factory rather than `XBProjector`. Was this by accident?

I'll have to change Spring Data's [`XmlBeamHttpMessageConverter`](https://github.com/spring-projects/spring-data-commons/blob/049970874dca2b648c9d2f3bfdd01f0e8a11de51/src/main/java/org/springframework/data/web/XmlBeamHttpMessageConverter.java#L46) to make it compatible with the latest bugfix releases. Any chance you make this interface public again?

**Comment by SvenEwald** [comment]
Ouch. I'm sorry for this inconvenience. This change just slipped through. I will make it public again.

**Comment by olivergierke** [comment]
1.4.12 seems to be in Maven Central already. I guess you're referring to 1.4.13 then?

**Comment by SvenEwald** [comment]
;-) I'm still in shock that this bug is that old...

**Comment by SvenEwald** [comment]
fixed in 1.4.13
