### ISSUE TITLE
Tried to use Example t04

### ISSUE THREAD

**Issue by khmarbaise** [SvenEwald/xmlbeam#48]
Hi,
I have tried to run your [example ](https://xmlbeam.org/t04.html) which unfortunately does not work which means it does not deliver information from the pom file (always `null`). After searching for a long time I found an [article which describes the usage](http://www.hascode.com/2014/07/xmlbeam-snippets-and-examples/) also but includes the usage of name spaces.
After searching for a longer time I found the solution which let the example correctly work:

```java
DefaultXMLFactoriesConfig config = new DefaultXMLFactoriesConfig();
config.setNamespacePhilosophy(NamespacePhilosophy.AGNOSTIC);
config.setOmitXMLDeclaration(false);

MavenPOM pom = new XBProjector(config, Flags.TO_STRING_RENDERS_XML).io().fromURLAnnotation(MavenPOM.class);pom.setName("New name");
for (Artifact artifact:pom.getDependencies()) {
  if (artifact.equals(pom.getProjectId())) {
      System.out.println("Hmm... your project depends on itself!");
  }
}
```
I think it would be a good idea to update the example accordingly.

**Comment by SvenEwald** [comment]
This gives me a little headache. The site examples are generated from JUnit tests, which would prevent a website deploy on failure. When I run example 4, it works. Could you post the pom.xml you used? The example uses the xmlbeam pom file.

**Comment by SvenEwald** [comment]
Still works for me
