### ISSUE TITLE
`createMapOf` doesn't work well when converting data to String

### ISSUE THREAD

**Issue by luanpotter** [SvenEwald/xmlbeam#55]
When using `createMapOf` with String, it should convert the text inside each tag and return the String requested. However, if the text is within a CDATA, blank is returned. Also, if I request specifically for the text() property, again, an empty string is returned.

The following test shows what I'm talking about:

https://gist.github.com/luanpotter/fb34841379ce48643ce035ca1f878884

**Comment by SvenEwald** [comment]
Fixed in 1.4.16. Thank you very much for reporting. Release follows soon.
