### ISSUE TITLE
Path with colon

### ISSUE THREAD

**Issue by PatientLiu** [SvenEwald/xmlbeam#57]
@XBAuto("/r:xml/y:example/content")
Hello:
Does a path similar to this format support conversion?
Does the path support special symbols?
Thank。

**Comment by PatientLiu** [comment]
@XBAuto("/r:xml/y:example/content")

This is the format I expected.

<r:xml>
  <y:example>
    <content>
    </content>
  </y:example>
</r:xml>

I looked at wiki, but I didn't find a solution.

**Comment by PatientLiu** [comment]
@XBAuto("/r:xml/y:example/content")

This is the format I expected.

<r:xml>
<y:example>
<content>
</content>
</y:example>
</r:xml>

I looked at wiki, but I didn't find a solution.

**Comment by PatientLiu** [comment]
@XBAuto("/r:xml/y:example/content")

This is the format I expected.
<r:xml><y:example><content></content></y:example></r:xml>

I looked at wiki, but I didn't find a solution.

**Comment by SvenEwald** [comment]
A colon is not a valid XML charater for entity names. Please learn about namespaces and come back. Just using a namespace prefix is not enough information for the xml builder to work. The prefix needs to be bound to a namespace.

**Comment by PatientLiu** [comment]
Thank you,

**Comment by OzeanWong** [comment]
What Im thinking about is create a xmlstring and replace some character with colon,but obviously It's not a good idea.

**Comment by PatientLiu** [comment]
Hello
How to create NAMESPACE objects

**Comment by PatientLiu** [comment]
Thank you. I know what to do.
