### ISSUE TITLE
Accessing whitespace-only text nodes returns "null" in 1.4.20

### ISSUE THREAD

**Issue by robertgrabowski** [SvenEwald/xmlbeam#61]
The behaviour of XMLBeam when accessing whitespace-only text nodes with `text()` has changed in 1.4.20.
 
Sample test code:

```java
public class TextNodeTest {

    interface Item {
        @XBRead("/item/text()")
        String getText();
    }

    @Test
    public void testWhitespaceOnlyTextNode() {
        final Item item = new XBProjector().onXMLString("<item> </item>").createProjection(Item.class);
        assertEquals(" ", item.getText());
    }
}
```

With 1.4.19, `item.getText()` returns `" "` (single space), and the test succeeds.
With 1.4.20, `item.getText()` returns `null`, and the test fails.

The same can be reproduced for any text nodes that contain nothing but a non-empty sequence of whitespace characters like space, tab and newline.

In our application, we can't change the XML, and we need to know precisely which text is present (even if it's only spaces). Is there any way with 1.4.20 to get the original contents of the part between `<item>` and `</item>`?

**Comment by SvenEwald** [comment]
This is a bug. I'll look into this.

**Comment by SvenEwald** [comment]
Java 9 broke the xml formatting when using a Transformer by inserting emtpy lines into the xml. It still ist broken afaik. In 1.4.20 I tried to fix the issue by removing nodes containing whitespace only. This worked, but broke the handling of these elements in the source document.
In 1.4.21 this change is reverted and the xml formatting in Java 9 and above is reimplented via XSLT.

**Comment by SvenEwald** [comment]
verified in 1.4.21.

**Comment by robertgrabowski** [comment]
@SvenEwald Thanks for fixing this so quickly!

---

However, we noticed that the fix caused another problem for us: 

We also serialize DOMs back into XML strings (via `DOMAccess.asString()`). Since 1.4.21, we get:

```
java.lang.IllegalArgumentException: Not supported: indent-number
	at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
	at org.xmlbeam.config.DefaultXMLFactoriesConfig.createTransformer(DefaultXMLFactoriesConfig.java:222)
        ...
```

The reason is that we use Xalan 2.7.2 as the XSLT processor, which makes `org.apache.xalan.processor.TransformerFactoryImpl` the default TransformerFactory. This factory doesn't support the "indent-number" attribute. Setting the "indent-number" attribute was introduced by the bugfix above. Until 1.4.20, `DOMAccess.asString()` and everything else seemed to work with Xalan.

I don't know whether XMLBeam is supposed to work with Xalan, and I'm also aware that the default TransformerFactory can be changed via system properties, so I don't know whether this constitutes a new bug. In any case, we were able to work around this problem (we didn't actually need `asString()`). I just wanted to mention it here.

**Comment by SvenEwald** [comment]
Which java version are you using? (The attribute is needed for java >=9 only.)

**Comment by robertgrabowski** [comment]
@SvenEwald We are using Java 8, but this may very well change in the near future.

**Comment by SvenEwald** [comment]
The problem should solve when you upgrade the java version or use the upcoming 1.4.22.
I disabled the setting of this attribute when java 8 or lower is used. AFAIK Xalan supports this attribute since java 9 and above.
