### ISSUE TITLE
Tutorial 1: MSN weather discontinued

### ISSUE THREAD

**Issue by fabtagon** [SvenEwald/xmlbeam#64]
Tutorial [E01: Printing some weather data](https://xmlbeam.org/t01.html#E01:_Printing_some_weather_data) uses MSN weather API which is unfortunately [discontinued](https://docs.microsoft.com/de-de/sharepoint/troubleshoot/apps/msn-weather-service-api-retired):

> Microsoft discontinued access to the MSN Weather Service API on April 15, 2016. Because of this change, the MSN Weather Service request URL is now disabled.

So the tutorial still gives a glimpse into the the xmlbeam API, but it does not run any longer. What do you think is the best way to proceed here?
- change example from webservice to hardcoded file
- change example from MSN to another web service (all that I've found are freemium and require some kind of API key)
- let things stay as they are

**Comment by SvenEwald** [comment]
Thanks a lot for the issue. I still have the original XML, cached via the unit test. I will include it into the project, so the tutorial can run again.
